### ISSUE TITLE
NotImplementedError: this Node If-If_xxxx has no value_infer

### ISSUE THREAD

**Issue by Thaslim** [ThanatosShinji/onnx-tool#66]
**Describe the bug**
Hi , I have exported the [SSD300_VGG16](https://pytorch.org/vision/main/models/generated/torchvision.models.detection.ssd300_vgg16.html) model to ONNX. When I try to profile using onnx_tool,  I get  **NotImplementedError: this Node If-If_3160 has no value_infer**

**To Reproduce**
```
import torch
import torch.onnx
import torchvision
import onnx_tool

dummy_input = torch.randn(1, 3, 300, 300)
model = torchvision.models.detection.ssd300_vgg16(weights=SSD300_VGG16_Weights.DEFAULT)
model.eval()
torch.onnx.export(model, dummy_input, "ssd300_vgg16.onnx",opset_version=11)
m = onnx_tool.Model("ssd300_vgg16.onnx")
m.graph.shape_infer()
m.graph.profile()
m.graph.print_node_map("ssd300_vgg16.csv")  
```

**Expected behavior**
csv file with profiled results

**Error**
```
/home/user/.local/lib/python3.6/site-packages/onnx_tool/node.py:2445: UserWarning: node If is not registed for profiling, return 0 Macs and 0 params as default. Use NODEPROFILER_REGISTRY to register your profiler for this node.
  warnings.warn(f'node {n.op_type} is not registed for profiling, return 0 Macs and 0 params as default. '
ERROR:root:Traceback (most recent call last):
  File "scripts/onnx_model_profile.py", line 27, in profile_model
    m.graph.shape_infer()  # update tensor shapes with new input tensor
  File "/home/user/.local/lib/python3.6/site-packages/onnx_tool/graph.py", line 844, in shape_infer
    node.shape_infer(itensors, otensors)
  File "/home/user/.local/lib/python3.6/site-packages/onnx_tool/node.py", line 155, in shape_infer
    self.value_infer(intensors, outtensors)
  File "/home/user/.local/lib/python3.6/site-packages/onnx_tool/node.py", line 158, in value_infer
    raise NotImplementedError(f'this Node {self.op_type}-{self.name} has no value_infer')
NotImplementedError: this Node If-If_3160 has no value_infer
```
I am profiling to get the list of OPs in this model. Please share if there are any workarounds to get past this error. Thank you

**Comment by ThanatosShinji** [comment]
Thanks for your report! It's already recorded.

Best Regards
________________________________
From: Thasleem ***@***.***>
Sent: Wednesday, January 31, 2024 6:09:52 AM
To: ThanatosShinji/onnx-tool ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ThanatosShinji/onnx-tool] NotImplementedError: this Node If-If_xxxx has no value_infer (Issue #66)


Describe the bug
Hi , I have exported the SSD300_VGG16<https://pytorch.org/vision/main/models/generated/torchvision.models.detection.ssd300_vgg16.html> model to ONNX. When I try to profile using onnx_tool, I get NotImplementedError: this Node If-If_3160 has no value_infer

To Reproduce
Steps to reproduce the behavior:

import torch
import torch.onnx
import torchvision
import onnx_tool

dummy_input = torch.randn(1, 3, 300, 300)
model = torchvision.models.detection.ssd300_vgg16(weights=SSD300_VGG16_Weights.DEFAULT)
model.eval()
torch.onnx.export(model, dummy_input, "ssd300_vgg16.onnx",opset_version=11)
m = onnx_tool.Model("ssd300_vgg16.onnx")
m.graph.shape_infer()
m.graph.profile()
m.graph.print_node_map("ssd300_vgg16.csv")


Expected behavior
csv file with profiled results

Error

/home/user/.local/lib/python3.6/site-packages/onnx_tool/node.py:2445: UserWarning: node If is not registed for profiling, return 0 Macs and 0 params as default. Use NODEPROFILER_REGISTRY to register your profiler for this node.
  warnings.warn(f'node {n.op_type} is not registed for profiling, return 0 Macs and 0 params as default. '
ERROR:root:Traceback (most recent call last):
  File "scripts/onnx_model_profile.py", line 27, in profile_model
    m.graph.shape_infer()  # update tensor shapes with new input tensor
  File "/home/user/.local/lib/python3.6/site-packages/onnx_tool/graph.py", line 844, in shape_infer
    node.shape_infer(itensors, otensors)
  File "/home/user/.local/lib/python3.6/site-packages/onnx_tool/node.py", line 155, in shape_infer
    self.value_infer(intensors, outtensors)
  File "/home/user/.local/lib/python3.6/site-packages/onnx_tool/node.py", line 158, in value_infer
    raise NotImplementedError(f'this Node {self.op_type}-{self.name} has no value_infer')
NotImplementedError: this Node If-If_3160 has no value_infer


I am profiling to get the list of OPs in this model. Please share if there are any workarounds to get past this error. Thank you

**Comment by ThanatosShinji** [comment]
@Thaslim One workaround for this. batched_nms creates this Op which I think it's a bad design of ONNX export.
Here are the python codes torchvision\ops\boxes.py  L79-L90:
```
def _batched_nms_coordinate_trick(
....
    # if boxes.numel() == 0:
    #     return torch.empty((0,), dtype=torch.int64, device=boxes.device)
```

You can try comment the if condition as I did in your local code. This will remove If in your model. I can get the correct MACs after this change.

Total                                            _                  34,985,765,664  100%        561,420,728  100%        35,637,878  100%        _              _

**Comment by Thaslim** [comment]
@ThanatosShinji Thank you, Appreciate your response.

**Comment by vfdff** [comment]
how to workaround the NotImplementedError for a custon node MatrixInverse, I tried the [workaround](https://github.com/ThanatosShinji/onnx-tool/issues/66#issuecomment-1959675695) but failed to solution it
